### ISSUE TITLE
Broken?

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/muddle#1]
Hello @taa01776,

I heard from @eswenson1 you said Muddle is broken.  Is it both the TOPS-20 and the old ITS version, or just one of them?  What is the nature of the breakage?

**Comment by eswenson1** [comment]
Lars, if you have an ITS tape image with the TOPS-20 <mdl.int> directory with the filenames Minard for ITS, I could load it on ES for Tim.

**Comment by eswenson1** [comment]
@lars I only loaded the ITS version on ES.

**Comment by larsbrinkhoff** [comment]
I put an mdlint.tape in http://lars.nocrew.org/its/

It's the files from the "its" branch in this repository, so some files have been removed and others are my own addition.

**Comment by larsbrinkhoff** [comment]
Some fixes are trivial, like increasing the symbol table.

Others are less obvious, like adding a closing `]`.  I'm not always sure I put it in the right place.

Then there's the fact that ITS MIDAS doesn't want to do some operations on unresolved symbols.  For example, in one place there's a one-bit right shift which I replaced with an addition.

**Comment by larsbrinkhoff** [comment]
I also tried to assemble the old MUDDLE version.  One problem was the use of `IFP` which ITS MIDAS doesn't know about.  Also, MIDAS warns about redefining `END`.

**Comment by larsbrinkhoff** [comment]
Eric, please let us know if you hear from Tim or Chris again.

**Comment by eswenson1** [comment]
I pinged both of them. Tim is very busy at the moment with work.  Haven't heard back yet from Chris.
